name: silverbowen/Quantiles
author:
  name: Silver Bowen
  email: silver.quickness@gmail.com
  url: null
copyright: 2015 Silver Bowen
description: 'This is a solution to the n-quantiles challenge I recently did for a job application. '
